# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependencies & Database
    init: |
      psql --command="CREATE USER debugger PASSWORD 'somestrong'" --command="\du"
      psql --command="CREATE DATABASE test_db OWNER debugger " --command="\l"
    command: PGPASSWORD=somestrong psql --username=debugger --host=localhost --list test_db

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
